parameters:
     facturama_client.class: Jplarar\FacturamaBundle\Services\FacturamaClient

services:
     Jplarar\FacturamaBundle\Services\FacturamaClient: "@facturama_client"
     facturama_client:
         class:     "%facturama_client.class%"
         arguments: ["%facturama_username%","%facturama_password%","%facturama_serie%","%facturama_expedition_place%","%facturama_product_code%","%facturama_env%"]
         autowire: true
         public: true


